# Build a machine learning model to predict user will click the ad or not based on his experience and estimated salary for a given dataset. 

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd
import numpy as np
import pickle
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('Social_Network_Ads.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [4]:
data.shape

(400, 5)

In [5]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
x = data.iloc[:, 2:4].values
y = data.iloc[:, -1:].values

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [8]:
x_test[0:4]

array([[   30, 87000],
       [   38, 50000],
       [   35, 75000],
       [   30, 79000]])

In [9]:
standard_x = StandardScaler()
x_train = standard_x.fit_transform(x_train)
x_test = standard_x.transform(x_test)

In [10]:
classifier = LogisticRegression(C = 1, penalty = 'l1')
classifier.fit(x_train, y_train)
y_pred_train = classifier.predict(x_train)
y_pred = classifier.predict(x_test)

In [11]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[56,  2],
       [ 5, 17]])

In [12]:
score = accuracy_score(y_test, y_pred)
score

0.9125

In [13]:
classifier.coef_

array([[2.05314057, 1.09850612]])