# For a given dataset predict number of bikes getting shared based on different parameters 

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('/home/admin1/machine_learning/week9/bike_sharing.csv')
data.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

In [3]:
data.drop(['instant','dteday'], axis = 1, inplace = True)
data.head()

season  yr  mnth  hr  holiday  weekday  workingday  weathersit  temp  \
0       1   0     1   0        0        6           0           1  0.24   
1       1   0     1   1        0        6           0           1  0.22   
2       1   0     1   2        0        6           0           1  0.22   
3       1   0     1   3        0        6           0           1  0.24   
4       1   0     1   4        0        6           0           1  0.24   

    atemp   hum  windspeed  casual  registered  cnt  
0  0.2879  0.81        0.0       3          13   16  
1  0.2727  0.80        0.0       8          32   40  
2  0.2727  0.80        0.0       5          27   32  
3  0.2879  0.75        0.0       3          10   13  
4  0.2879  0.75        0.0       0           1    1

In [4]:
x = data.iloc[:,0:-1].values
y = data.iloc[:,-1:].values

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [6]:
x_train.shape

(13903, 14)

In [7]:
x_test.shape

(3476, 14)

In [9]:
#Fitting polynomial Regression
polyreg = PolynomialFeatures(degree = 2) 
x_train_poly = polyreg.fit_transform(x_train)
x_test_poly = polyreg.transform(x_test)

poly_reg = LinearRegression()
poly_reg.fit(x_train_poly, y_train) 

y_pred = poly_reg.predict(x_test_poly)
y_pred

array([[  7.],
       [  5.],
       [743.],
       ...,
       [ 34.],
       [  7.],
       [371.]])

In [10]:
#Calculating the errors of polynomial Regresssion
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

8.424026734671961e-11

In [11]:
#Checking First 5 Samples from the predictions made on test data
y_pred[0:5]

array([[  7.],
       [  5.],
       [743.],
       [208.],
       [333.]])

In [12]:
#Checking First 5 Samples i.e the actual output of the test data
y_test[0:5]

array([[  7],
       [  5],
       [743],
       [208],
       [333]])