In [ ]:
""" Write a Python program to create a contiguous flattened array. 
Original array:
[[10 20 30] 
[20 40 50]] 
New flattened array: 
[10 20 30 20 40 50]"""

import numpy as np
x=[ ]
n=int(input('Enter the number of rows-'))
m=int(input('Enter the number of coloumns-'))
for i in range(n):
	x.append([ ])
for i in range(n):
	for j in range(m):
		x[i].append(j)
		x[i][j]=int(input('Enter the elements-'))
z=np.array(x)
print(z)
y=np.ravel(z) #ravel will convert any given array to contiguous  flattened array(A contiguous array is an array stored in an unbroken block of memory)
print('The new flattened array is-',y)