In [ ]:
"""Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array. 
Expected Output:
Original array elements: 
[[ 0 1 2 3] 
[ 4 5 6 7] 
[ 8 9 10 11]] 
New array elements:
[[ 0 3 6 9] 
[12 15 18 21] 
[24 27 30 33]]"""

import numpy as np
x=[ ]
n=int(input('Enter the number of rows-'))
m=int(input('Enter th number of coloumns-'))
for i in range(n):
	x.append([ ])
for i in range(n):
	for j in range(m):
		x[i].append(j)
		x[i][j]=int(input('Enter the elements-'))
y=np.array(x)
print(y)

k=int(input('Enter the number to multiply with the array-'))
for i in np.nditer(y,op_flags=['readwrite']):  #nditer is an iterator object in numpy that provides many ways to visit all the elements of one or more array also by default treats the input array as readonly hence we specify readwrite using operand flags
	i[...]=k*i  #i[...] is ellipes which is similar to slicing & is used for slicing multidimensional array
print(y)