In [ ]:
"""Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere. 
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.] 
[ 0. 0. 1.]]"""


import numpy as np
n=int(input('Enter number of rows-'))
m=int(input('Enter the number of coloumns-'))
x = np.eye(n,m) #np.eye will return an array with  ones on the diagonals and zeros elsewhere
print(x)