In [ ]:
"""Write a Python program to create a 2d array with 1 on the border and 0 inside.  
Expected Output:
Original array: 
[[ 1. 1. 1. 1. 1.] 
[ 1. 1. 1. 1. 1.] 
[ 1. 1. 1. 1. 1.] 
[ 1. 1. 1. 1. 1.] 
[ 1. 1. 1. 1. 1.]] 
1 on the border and 0 inside in the array 
[[ 1. 1. 1. 1. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 1. 1. 1. 1.]]
"""
import numpy as np
n=int(input('Enter the number of rows of array-')) #rows of the 2d array
m=int(input('Enter the number of coloumns of array-')) #coloumns of the 2d array
x=np.ones((n,m))#assigning all the values of 2d array to 1
print(x)
x[1:-1,1:-1]=0 #changing the value of row from 1 to-1 to zero & changing the value of coloumn from 1 to -1 to zero 
print(x)