In [ ]:
"""Write a Python program to add a border (filled with 0's) around an existing array. 
Expected Output:
Original array: 
[[ 1. 1. 1.] 
[ 1. 1. 1.] 
[ 1. 1. 1.]] 
1 on the border and 0 inside in the array 
[[ 0. 0. 0. 0. 0.] 
[ 0. 1. 1. 1. 0.] 
[ 0. 1. 1. 1. 0.] 
[ 0. 1. 1. 1. 0.] 
[ 0. 0. 0. 0. 0.]]
"""

import numpy as np
m=int(input('Enter the number of rows-'))
n=int(input('Enter the number of coloumns-'))
x=np.ones((n,m))
print(x)
b=int(input('Enter the constant value for the border-'))
a=np.pad(x,pad_width=1,mode='constant',constant_values=b) #x-array, pad_width-no of rows & col. to which we want to apply border,mode-constant(pads with a constant value provided by the user)
print(a)