In [ ]:
"""Write a Python program to change the data type of an array. 
Expected Output:
[[ 2 4 6]
[ 6 8 10]] 
Data type of the array x is: int32 
New Type: float64 
[[ 2. 4. 6.] 
[ 6. 8. 10.]]"""

import numpy as np
x=[ ]
n=int(input('Enter the number of rows-'))
m=int(input('Enter the number of coloumns-'))
for i in range(n):
	x.append([ ])
for i in range(n):
	for j in range(m):
		x[i].append(j)
		x[i][j]=int(input('Enter the elements-'))
y=np.array(x)
print(y)
print('Data type of the array y is-',(y.dtype))
z=np.array(x,dtype='float64')
print()
print(z)
print('New Data  Type is-',(z.dtype))