In [ ]:
"""Create a 3x3 matrix with values ranging from 2 to 10.  
Expected Output:
[[ 2 3 4] 
[ 5 6 7] 
[ 8 9 10]] """

import numpy as np
n=int(input('Enter a number-')) #Take the number up to which you want to create arange
k=n+1 #Increase the value by 1 to include the entered number
m=int(input('Enter the number of rows-')) #Enter the number of rows u want in a matrix
l=int(input('Enter the number of coloumns-')) #Enter the number of coloumns in a matrix
try:
    x=np.arange(2,k).reshape(m,l) #If a matrix can be created with user input coloumns and rows 
    print(x) #print the matrix
except ValueError: #If the matrix cannot be created with user input coloumns and rows raise a value error
    print('Cannot Create a matrix with given input')
