In [ ]:
""" Write a Python program to create an array which looks like below array. 
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]"""

import numpy as np
n=int(input('Enter the number of rows-'))
m=int(input('Enter the number of coloumns-'))
k=int(input('Enter the diagonal number-')) #k is actually a subdiagonal that is a diagonal below the main diagonal
x = np.tri(n,m,k) #returns array with ones at and below the given diagonal and zeros elsewhere.
print(x)