In [ ]:
"""Write a Python program to convert a list and tuple into arrays. 
List to array:
[1 2 3 4 5 6 7 8] 
Tuple to array:
[[8 4 6] 
[1 2 3]]
"""

import numpy as np
x=[ ]
n=int(input('Enter the number of elements-'))
for i in range(n):
    a=int(input('Enter the elements-'))
    x.append(a)
print(x)
print()
b=np.array(x) #converting list to numpy array
print(b)

y=[ ] #creating a list to take different dimensions and then converting the list to tuple
n=int(input('Enter the number of rows-'))
m=int(input('Enter the number of coloumns-'))
for i in range(n):
    y.append([ ])
for i in range(n):
    for j in range(m):
        y[i].append(j)
        y[i][j]=int(input('Enter the elements-'))
z=tuple(y) #converting the list to tuple
print(z)
k=np.array(z) #converting the tuple to array
print(k)