In [ ]:
"""Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern. 
Checkerboard pattern:
[[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0]]
"""

import numpy as np
m=int(input('Enter the number of rows-'))
n=int(input('Enter the number of coloumns-'))
x=np.zeros((n,m))
x[1::2,::2]=1 #Slice from 1st index row till 1+2+2… and fill all columns with 1 starting from 0th to 0+2+2… 
x[::2,1::2]=1 #Slice from 0th row till 0+2+2… and fill all columns with 1 starting from 1 to 1+2+2+…..
print(x)